
# Details for the RSS feed generator
url:            'https://dnszhou.github.io/'
author:         'Dennis Zhou'

name: 遠辰
title: DnsZhou Blog
email: zt1020@yeah.net
meta_description: "Your New Jekyll Site, Blogging about stuffs"
description: > # this means to ignore newlines until "baseurl:"
  描述暂空
baseurl: "/"
twitter_username: DnsZhou
github_username:  DnsZhou

# Build settings
markdown: kramdown
theme: minima
paginate: 15
plugins:
  - jekyll-feed
  - jekyll-paginate